### ISSUE TITLE
Add flake8 linting

### ISSUE THREAD

**Issue by jdrempel** [jdrempel/atmos#20]
For formatting. The "old saying" is that it's better to pick a random coding style and enforce it than to not have one at all. PEP8 seems like a pretty good style to enforce as it's the "standard" style.

[flake8](https://flake8.pycqa.org/en/latest/)

An alternative is [Black](https://github.com/psf/black).

**Comment by majabojarska** [comment]
Just a heads up that *Flake8* is a linter and *Black* is a formatter - both are PEP8-compatible. Both could be used same time, e.g. *Black* for formatting the codebase and then *Flake8* to lint the formatted code.

**Comment by jdrempel** [comment]
Closed by #23 (oddly enough)
